### PR TITLE
Added sound effects

### PR DESCRIPTION
**Pull request by jaybhatia55**
Added 3 new sound effects

### CODE REVIEW

**Comment by Legedith** [comment]
The sounds effects currently in the repo have one or more pop-culture references. Some are popular dialogues while other are from iconic scenes.
Can you add some which aligns with the effects currently in the repo?

**Comment by jaybhatia55** [comment]
Added a audio of dialog from The Pursuit of Happyness movie

**Comment by Legedith** [comment]
This one sounds nice. Please remove the first three that you added and add at least 2-3 more effects like this one.

**Comment by jaybhatia55** [comment]
added a dialog from movie The Waterboy and removed extra audios

**Pull request merged**
